WMSApp/WMSWebApp/ViewModels/PO/PoSrnViewModel.cs
namespace WMSWebApp.ViewModels.PO
{
    public class PoSrnViewModel
    {
        public int Id { get; set; }
        public string LoginBranch { get; set; }
        public string SenderCompany { get; set; }
        public string Branch { get; set; }
        public string PurchaseOrder { get; set; }
        public string ItemCode { get; set; }
        public string SubItemCode { get; set; }
        public string SubItemName { get; set; }
        public string MaterialDescription { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal Amt { get; set; }
        public bool IsDeleted { get; set; }
        public int Sno { get; set; }

        public string SendingTo { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/PO/PoViewModel.cs
using Domain.Model.PO;
using System;
using System.Collections.Generic;

namespace WMSWebApp.ViewModels.PO
{
    public class PoViewModel
    {
        public DateTime PODate { get; set; }

        public string PONumber { get; set; }

        public string POCatrgory { get; set; }

        public List<StockTransferCategory> stockTransferCategories { get; set; }

        public List<SalePO> salePOCategories { get; set; }

        public List<SRNPOCategory> sRNPOCategories { get; set; }


        public List<ServiceOrderCategory> serviceOrderCategories { get; set; }



    }
}

WMSApp/WMSWebApp/ViewModels/PO/PolistViewModel.cs
namespace WMSWebApp.ViewModels.PO
{
    public class PolistViewModel
    {
        public int Id { get; set; }
        public string PoNumber { get; set; }
        public string stockTransferPOCatagry { get; set; }
        public string stockTransferPoSendingTo { get; set; }
        public string stockTransferPoItem { get; set; }
        public string subItemCode { get; set; }
        public string stockTransferPoSubitem { get; set; }
        public string stockTransferPoQty { get; set; }
        public string stockTransferPoAmt { get; set; }
        public string stockTransferPoSerialNumber { get; set; }
        public string serviceCategory { get; set; }
        public string salePo { get; set; }
        public string saleDate { get; set; }
        public string ServiceRequestNumber { get; set; }
        public string invNumber { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/PO/PurchaseOrderViewModel.cs
using Domain.Model;
using System.Collections.Generic;

namespace WMSWebApp.ViewModels.PO
{
    public class PurchaseOrderViewModel
    {
        public List<Branch> listBranch { get; set; }
        public List<SenderCompanyNameDb> listSenderCompany { get; set; }
        public List<ItemDb> listItem { get; set; }

        public List<SubItemDb> listSubItem { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/PO/SRNPOCategory.cs
namespace WMSWebApp.ViewModels.PO
{
    public class SRNPOCategory
    {
        public string SrnSerialNumber { get; set; }
        public string SrnPOCategory { get; set; }
        public string SrnPOSendingTo { get; set; }

        public string SrnPOItem { get; set; }
        public string SrnPOSubItem { get; set; }

        public int SrnPOQty { get; set; }
        public string SrnPOSrnCause { get; set; }

        public string SubItemCode { get; set; }

        public string InvoiceNo { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/PO/SalePOCategory.cs
namespace WMSWebApp.ViewModels.PO
{
    public class SalePO
    {
        public string PONumber { get; set; }
        public string SalePOCategory { get; set; }
        public string SalePOSendingTo { get; set; }
        public string SalePOItem { get; set; }

        public string SalePOSubItem { get; set; }
        public int SalePOQty { get; set; }
        public string SalePOAmt { get; set; }
        public string SalePOSerialNumber { get; set; }
        public string SubItemCode { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/PO/ServiceOrderCategory.cs
namespace WMSWebApp.ViewModels.PO
{
    public class ServiceOrderCategory
    {
        public string ServiceOrderPOCategory { get; set; }
        public string ServiceOrderPOSendingTo { get; set; }
        public string ServiceOrderPOItem { get; set; }
        public string ServiceOrderPOSubitem { get; set; }

        public int ServiceOrderPOQty { get; set; }
        public string ServiceOrderPOServiceCatagry { get; set; }
        public string ServiceOrderPOServiceRequestNumber { get; set; }

        public string ServiceOrderPOSalePO { get; set; }
        public string ServiceOrderPOSaleDate { get; set; }

        public string ServiceOrderPOAmt { get; set; }

        public string ServiceOrderPOSerialNumber { get; set; }
        public string SubItemCode { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/PO/StockTransferCategory.cs
namespace WMSWebApp.ViewModels.PO
{
    public class StockTransferCategory
    {
        public string StockTransferPOCategory { get; set; }
        public string StockTransferPOSendingTo { get; set; }
        public string StockTransferPOItem { get; set; }
        public string StockTransferPOSubItem { get; set; }
        public int StockTransferPOQty { get; set; }
        public string StockTransferPOAmt { get; set; }
        public string StockTransferPOSerialNumber { get; set; }
        public string SubItemCode { get; set; }
    }
}

WMSApp/WMSWebApp/Controllers/PoController.cs
using Application.Services;
using Application.Services.PO;
using AutoMapper;
using Domain.Model;
using Domain.Model.PO;
using ExcelDataReader;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WMS.Data;
using WMS.Web.Framework.Infrastructure.Extentsion;
using WMSWebApp.ViewModels.PO;

namespace WMSWebApp.Controllers
{
    [Authorize]
    public class PoController : BaseAdminController
    {

        #region Fields

        private readonly IMapper _mapper;
        private readonly IPurchaseOrder _purchaseOrder;
        private readonly ISubItemHelper _SubItemHelper;
        private readonly IBranchHelper _BranchHelper;
        private readonly IItemHelper _ItemHelper;
        private readonly ISenderCompany _senderCompany;
        private readonly ISalePo _salePo;
        private readonly IStockTransferPo _stockTransferPo;
        private readonly IServiceOrderPo _serviceOrderPO;
        private readonly ISrnPo _srnPo;
        private readonly ICustomerHelper _customerHelper;
        private readonly IWorkContext _workContext;
        #endregion

        #region Ctor
        public PoController(IMapper mapper, IPurchaseOrder purchaseOrder, ISubItemHelper SubItemHelper, IBranchHelper BranchHelper, IItemHelper ItemHelper, ISenderCompany senderCompany,
            ISalePo salePo, IStockTransferPo stockTransferPo, ISrnPo srnPo, ICustomerHelper customerHelper, IServiceOrderPo serviceOrderPo, IWorkContext workContext)
        {
            _SubItemHelper = SubItemHelper;
            _mapper = mapper;
            _purchaseOrder = purchaseOrder;
            _BranchHelper = BranchHelper;
            _ItemHelper = ItemHelper;
            _senderCompany = senderCompany;
            _salePo = salePo;
            _stockTransferPo = stockTransferPo;
            _serviceOrderPO = serviceOrderPo;
            _srnPo = srnPo;
            _customerHelper = customerHelper;
            _workContext = workContext;
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public virtual IActionResult List(DataSourceRequest request, string category)
        {
            switch (category)
            {

                case "StockTransfer PO":
                    var result = _stockTransferPo.GetDetails(category, request.Page - 1, request.PageSize);
                    var gridData = new DataSourceResult()
                    {
                        Data = result.Select(x =>
                        {
                            PolistViewModel m = new PolistViewModel();
                            m.Id = x.Id;
                            m.PoNumber = x.PONumber;
                            m.stockTransferPOCatagry = x.StockTransferPOCategory;
                            m.stockTransferPoSendingTo = x.StockTransferPOSendingTo;
                            m.stockTransferPoItem = x.StockTransferPOItem;
                            m.stockTransferPoSubitem = x.StockTransferPOSubItem;
                            m.stockTransferPoQty = x.StockTransferPOQty.ToString();
                            m.stockTransferPoAmt = x.StockTransferPOAmt;
                            m.stockTransferPoSerialNumber = x.StockTransferPOSerialNumber;
                            m.serviceCategory = "Not Applicable";
                            m.salePo = "Not Applicable";
                            m.saleDate = "Not Applicable";
                            m.ServiceRequestNumber = "Not Applicable";
                            m.subItemCode = x.SubItemCode;
                            m.invNumber = "";
                            return m;
                        }),

                        Total = result.TotalCount
                    };
                    return Json(gridData);
                case "Sale PO":
                    var result1 = _salePo.GetDetails(category, request.Page - 1, request.PageSize);
                    var gridData1 = new DataSourceResult()
                    {
                        Data = result1.Select(x =>
                        {
                            PolistViewModel m = new PolistViewModel();
                            m.Id = x.Id;
                            m.PoNumber = x.PONumber;
                            m.stockTransferPOCatagry = x.SalePOCategory;
                            m.stockTransferPoSendingTo = x.SalePOSendingTo;
                            m.stockTransferPoItem = x.SalePOItem;
                            m.stockTransferPoSubitem = x.SalePOSubItem;
                            m.stockTransferPoQty = x.SalePOQty.ToString();
                            m.stockTransferPoAmt = x.SalePOAmt;
                            m.stockTransferPoSerialNumber = x.SalePOSerialNumber;
                            m.serviceCategory = "Not Applicable";
                            m.salePo = "Not Applicable";
                            m.saleDate = "Not Applicable";
                            m.ServiceRequestNumber = "Not Applicable";
                            m.subItemCode = x.SubItemCode;
                            m.invNumber = "";
                            return m;
                        }),
                        Total = result1.TotalCount
                    };
                    return Json(gridData1);
                case "SRN PO":
                    var result2 = _srnPo.GetDetails(category, request.Page - 1, request.PageSize);
                    var gridData2 = new DataSourceResult()
                    {
                        Data = result2.Select(x =>
                        {
                            PolistViewModel m = new PolistViewModel();
                            m.Id = x.Id;
                            m.PoNumber = x.PONumber;
                            m.stockTransferPOCatagry = x.SrnPOCategory;
                            m.stockTransferPoSendingTo = x.SrnPOSendingTo;
                            m.stockTransferPoItem = x.SrnPOItem;
                            m.stockTransferPoSubitem = x.SrnPOSubItem;
                            m.stockTransferPoQty = x.SrnPOQty.ToString();
                            m.stockTransferPoAmt = "0";
                            m.stockTransferPoSerialNumber = x.SrnSerialNumber;
                            m.serviceCategory = "Not Applicable";
                            m.salePo = "Not Applicable";
                            m.saleDate = "Not Applicable";
                            m.ServiceRequestNumber = "Not Applicable";
                            m.subItemCode = x.SubItemCode;
                            m.invNumber = x.InvoiceNo;
                            return m;
                        }),
                        Total = result2.TotalCount
                    };
                    return Json(gridData2);
                case "ServiceOrder PO":
                    var result3 = _serviceOrderPO.GetDetails(category, request.Page - 1, request.PageSize);
                    var gridData3 = new DataSourceResult()
                    {
                        Data = result3.Select(x =>
                        {
                            PolistViewModel m = new PolistViewModel();
                            m.Id = x.Id;
                            m.PoNumber = x.PONumber;
                            m.stockTransferPOCatagry = x.ServiceOrderPOCategory;
                            m.stockTransferPoSendingTo = x.ServiceOrderPOSendingTo;
                            m.stockTransferPoItem = x.ServiceOrderPOSubitem;
                            m.stockTransferPoSubitem = x.ServiceOrderPOSubitem;
                            m.stockTransferPoQty = x.ServiceOrderPOQty.ToString();
                            m.stockTransferPoAmt = x.ServiceOrderPOAmt;
                            m.stockTransferPoSerialNumber = x.ServiceOrderPOSerialNumber;
                            m.serviceCategory = x.ServiceOrderPOServiceCatagry;
                            m.salePo = "Not Applicable";
                            m.saleDate = "Not Applicable";
                            m.ServiceRequestNumber = x.ServiceOrderPOServiceRequestNumber;
                            m.subItemCode = x.SubItemCode;
                            m.invNumber = "";
                            return m;
                        }),
                        Total = result3.TotalCount
                    };
                    return Json(gridData3);

            }
            return Json("");
        }

        public ActionResult Create()
        {
            PurchaseOrderViewModel purchaseOrderViewModel = new PurchaseOrderViewModel();
            var listSubItem = _SubItemHelper.GetAllSubItem();
            var listBranch = _BranchHelper.GetAllBranch();
            var listItem = _ItemHelper.GetAllItem();
            var listSendCompany = _senderCompany.GetAllSenderCompanies();
            //  var listCategory = "";
            listSendCompany.Insert(0, new SenderCompanyNameDb { Id = 0, Sender_Company_Name = "Select" });
            listBranch.Insert(0, new Branch { Id = 0, BranchName = "Select" });
            listItem.Insert(0, new ItemDb { Id = 0, ItemName = "Select" });
           // listSubItem.Insert(0, new SubItemDb { Id = 0, SubItemName = "Select" });
            ViewBag.ListofSenderCompany = listSendCompany.ToList();
            ViewBag.listBranch = listBranch.ToList();
            ViewBag.listItem = listItem.ToList();
            ViewBag.listSubItem = listSubItem.ToList();

            purchaseOrderViewModel.listItem = listItem;
            purchaseOrderViewModel.listSubItem = listSubItem;

WMSApp/WMSWebApp/Views/Po/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Style{

<link href="~/lib/kendoUi/2021/styles/kendo.common.min.css" rel="stylesheet" />
<link href="~/lib/kendoUi/2021/styles/kendo.default.min.css" rel="stylesheet" />
<link href="~/lib/kendoUi/2021/styles/kendo.default.mobile.min.css" rel="stylesheet" />
<link href="~/lib/jquery-ui/jquery-ui.min.css" rel="stylesheet" />
<link rel="stylesheet" href="~/lib/plugins/select2/css/select2.min.css">
<link rel="stylesheet" href="~/lib/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
<link rel="stylesheet" href="~/lib/plugins/toastr/toastr.min.css" />
<style>

    .ui-autocomplete {
        /*position: absolute;*/
        cursor: default;
        z-index: 1099 !important;
        max-height: 200px;
        overflow-y: scroll;
        overflow-x: hidden;
    }

    .ui-datepicker {
        z-index: 1099 !important;
    }

    .ui-autocomplete-loading {
        background: white url("../img/ajax-loader.gif") right center no-repeat;
    }
</style>
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                @*  <h1>Create Pick Slip</h1>*@
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Master</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Po list</h3>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Doc Type</label>
                                <select class="form-control" id="doctypelist">
                                    @* <option value="Select">Select</option>*@
                                    <option value="StockTransfer PO">StockTransfer PO</option>
                                    <option value="Sale PO">Sale PO</option>
                                    <option value="SRN PO">SRN PO</option>
                                    <option value="ServiceOrder PO">ServiceOrder PO</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <h3>Upload Bulk</h3>
                            <form id="fileUploadForm" method="post" enctype="multipart/form-data" asp-controller="Po" asp-action="OnPostMyUploader">
                                <div>
                                    <div class="form-group">
                                        <label for="exampleInputFile">Upload file:</label>
                                        <div class="input-group">
                                            <div class="custom-file">
                                                <input type="file" id="uploadFile" name="uploadFile" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <button type="submit" value="Upload" class="btn btn-primary"><i class="fa fa-cloud-upload" aria-hidden="true"></i> Upload</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-primary" type="button" id="search">Search</button>
                        </div>
                    </div>
                    <hr />
                    <div class="row">
                        <div id="pick-grid">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal fade" id="pleaseWait" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Please Wait..</h5>

            </div>
            <div class="modal-body">
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
                </div>
            </div>
            @*<div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
                </div>*@
        </div>
    </div>
</div>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

<environment include="Development">
    <script src="~/lib/kendoUi/2021/js/kendo.all.min.js"></script>
    <script src="~/lib/kendoUi/2021/js/jszip.min.js"></script>
    <script src="~/js/common.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/plugins/select2/js/select2.full.min.js"></script>
    @*  <script src="~/js/po/po.js" asp-append-version="true"></script>*@
    @*   <script src="~/js/PickSlip/pickslipprocess.js" asp-append-version="true"></script>*@
    <script src="~/lib/plugins/toastr/toastr.min.js"></script>
</environment>
<environment exclude="Development">
    <script src="~/lib/kendoUi/2021/js/kendo.all.min.js"></script>
    <script src="~/lib/kendoUi/2021/js/jszip.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/lib/plugins/select2/js/select2.full.min.js"></script>
    <script src="~/js/common.min.js"></script>
    @*    <script src="~/js/po/po.js" asp-append-version="true"></script>*@
    <script src="~/lib/plugins/toastr/toastr.min.js"></script>
</environment>
<script type="text/javascript">
    function additionalData()
    {
       var data =
       {
                category: $("#doctypelist").val(),
       }
       addAntiForgeryToken(data);
       return data;
     }
     $(document).ready(function ()
     {
         $('#search').click(function () {             
                //search
                var grid = $('#pick-grid').data('kendoGrid');
                grid.dataSource.read();
                return false;
          });
             var initialLoad = true;
              $("#pick-grid").kendoGrid({
        toolbar: ["excel"],
        excel: {
            fileName: "PoList.xlsx",
            proxyURL: "/Po/List",
            filterable: true
        },
        dataSource: {

            transport: {
                read: {
                    url: "/Po/List",
                    type: "POST",
                    dataType: "json",
                    data: additionalData,
                    complete: function (result) {
                        console.log("Remote built-in transport", result);
                        if (result.status == 401) {
                            /* document.location.href = "@Html.Raw(Url.Action("Index", "AccessDenied"))";*/
                        }
                    }

                }
            },
            schema: {
                data: "Data",
                total: "Total",
                errors: "Errors"
            },
            error: function (e) {
                //display_kendoui_grid_error(e);
                // Cancel the changes
                console.log(e)
                this.cancelChanges();
            },
            pageSize: 20,
            sortable: true,
            serverPaging: true,
            serverSorting: true,
            requestStart: function () {
                if (initialLoad) //<-- if it's the initial load, manually start the spinner
                    kendo.ui.progress($("#booking-grid"), true);
            },
            requestEnd: function () {
                if (initialLoad)
                    kendo.ui.progress($("#booking-grid"), false);
                initialLoad = false; //<-- make sure the spinner doesn't fire again (that would produce two spinners instead of one)

            },

        },
        //selectable: 'raw',
        //change: onChange,
        height: 350,
        pageable: {
            refresh: true,
            pageSizes: true
        },

        scrollable: true,
        columns: [{
            field: "Id",
            title: "Id",
            width: 50
        },
        {
            field: "PoNumber",
            title: "Po Number",
            width: 100
        },
           {
            field: "stockTransferPOCatagry",
            title: "PO Catagry",
            width: 100
        },
        {
            field: "stockTransferPoSendingTo",
            title: "Sending To",
            width: 100
        },
        {
            field: "stockTransferPoItem",
            title: "Item",
            width: 100
        },
         {
            field: "stockTransferPoSubitem",
            title: "Sub Item",
            width: 100
        },
        {
            field: "stockTransferPoQty",
            title: "Qty",
            width: 100
        },
       {
            field: "stockTransferPoSerialNumber",
            title: "Serial Number",
            width: 100
        },
        {
            field: "subItemCode",
            title: "SubItem Code",
            width: 100
        },


            //{
            //    field: "Unit",
            //    title: "Unit",
            //    width: 100
            //},


            //{
            //    field: "Amt",
            //    title: "Amt",
            //    width: 100
            //},


        ],

    });
     });

      $("#fileUploadForm").submit(function(e) {
            e.preventDefault();
            //debugger;
            var file = $('#uploadFile').val();
            if (!(/\.(xlsx|xls|xlsm)$/i).test(file)) {
                alert('Please upload valid excel file .xlsx, .xlsm, .xls only.');
                $("#uploadFile").val('');
            } else {
                var data = new FormData();
                data.append("importFile", $("#uploadFile")[0].files[0]);
                $.ajax({
                    type: 'post',
                    url: "/Po/OnPostMyUploader",
                    data: data,
                    processData: false,
                    contentType: false
                }).done(function(result) {
                    if (result.Status === 1) {
                        alert(result.Message);
                        location.reload();
                    }
                    else {
                        alert(result.Message);
                    }
                });
            }
        });








</script>
    }