WMSApp/WMSWebApp/ViewModels/Intrasit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WMSWebApp.ViewModels
{
    public class Intrasitc
    {
        public int Id { get; set; }
        public string LoginBranch { get; set; }
        public string SenderCompany { get; set; }
        [Display(Name = "Sender Branch")]
        public string Branch { get; set; }
        [Display(Name = "Purchase Order")]
        public string PurchaseOrder { get; set; }
        public string ItemCode { get; set; }
        public string SubItemCode { get; set; }
        public string SubItemName { get; set; }
        [Display(Name = "Material Description")]
        public string MaterialDescription { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal Amt { get; set; }
        public DateTime ETA { get; set; }
        public bool IsDeleted { get; set; }
        public int Sno { get; set; }
        public bool AllowGRN { get; set; }

        public string subItemCodeVal { get; set; }

    }
}

WMSApp/WMSWebApp/Controllers/IntrasitController.cs
using Application.Services;
using AutoMapper;
using ClosedXML.Excel;
using Domain.Model;
using ExcelDataReader;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WMS.Data;
using WMSWebApp.ViewModels;
using static System.Net.WebRequestMethods;

namespace WMSWebApp.Controllers
{
    public class IntrasitController : Controller
    {
        private readonly IIntrasitHelper _IntrasitHelper;
        private readonly IMapper _mapper;
        private readonly IWorkContext _workContext;
        public IntrasitController(IIntrasitHelper intrasitHelper, IMapper mapper, IWorkContext workContext)
        {
            _IntrasitHelper = intrasitHelper;
            _mapper = mapper;
            _workContext = workContext;
        }

        public IActionResult Index()
        {
            List<Intrasitc> intrasitcs = new List<Intrasitc>();
            try
            {
                var data = _IntrasitHelper.GetAllIntrasit();
                for (int i = 0; i < data.Count; i++)
                {
                    Intrasitc objDate = new Intrasitc();
                    objDate.Id = data[i].Id;
                    objDate.PurchaseOrder = data[i].PurchaseOrder;
                    objDate.Branch = data[i].Sender_Branch;
                    objDate.ItemCode = data[i].Item_Code;
                    objDate.SubItemCode = data[i].SubItem_Code;
                    objDate.MaterialDescription = data[i].Material_Description;
                    objDate.Qty = data[i].Qty;
                    objDate.Unit = data[i].Unit;
                    objDate.Amt = data[i].Amt;
                    intrasitcs.Add(objDate);
                }
            }
            catch (Exception ex)
            {

            }
            return View(intrasitcs);

        }

        // GET: CompaniesController/Create
        public ActionResult Create()
        {
            IntransitViewModel intransitViewModel = new IntransitViewModel();
            List<Intrasitc> intrasitcs = new List<Intrasitc>();
            intransitViewModel.intrasitcList = intrasitcs;
            intransitViewModel.intrasitc = new Intrasitc();
            try
            {
                //var data = _IntrasitHelper.GetAllIntrasit();
                //for (int i = 0; i < data.Count; i++)
                //{
                //    Intrasitc objDate = new Intrasitc();
                //    objDate.Id = data[i].Id;
                //    objDate.Amt = data[i].Amt;
                //    objDate.Qty = data[i].Qty;
                //    objDate.ETA = data[i].ETA;
                //    objDate.MaterialDescription = data[i].MaterialDescription;
                //    objDate.Branch = data[i].Branch;
                //    objDate.ItemCode = data[i].Item_Code;
                //    objDate.SubItemName = data[i].SubItem_Name;
                //    objDate.SubItemCode = data[i].SubItem_Code;
                //    objDate.PurchaseOrder = data[i].PurchaseOrder;
                //    intrasitcs.Add(objDate);
                //}
                var listBranch = _IntrasitHelper.GetAllBranches();
                var listCompany = _IntrasitHelper.GetAllCompany();
                var listItem = _IntrasitHelper.GetAllItem();
                listCompany.Insert(0, new CompanyDb { Id = 0, CompanyName = "Select" });
                listBranch.Insert(0, new Branch { Id = 0, BranchName = "Select" });
                listItem.Insert(0, new ItemDb { Id = 0, ItemName = "Select" });
                ViewBag.ListofCompany = listCompany;
                ViewBag.listBranch = listBranch;
                ViewBag.listItem = listItem;
                //intransitViewModel.listSenderBranch = listBranch.ToList();
                //intransitViewModel.listSenderCompany = listCompany.ToList();
                // intrasitcs = _mapper.Map<List<Intrasitc>>(data);
            }
            catch (Exception ex)
            {
                throw;
            }
            return PartialView(intransitViewModel);
            //return View();
        }

        // POST: CompaniesController/Create
        [HttpPost]
        public JsonResult Create([FromBody] IntransitViewModel intransitViewModel)
        {
            try
            {
                // var intrasit = _mapper.Map<IntrasitDb>(intrasitc);
                var branch = _workContext.GetCurrentBranch().Result;
                foreach (var item in intransitViewModel.intrasitcList)
                {
                    IntrasitDb intrasitDb = new IntrasitDb();
                    intrasitDb.Sender_Branch = item.Branch;
                    intrasitDb.PurchaseOrder = item.PurchaseOrder;
                    intrasitDb.Sender_Company = item.SenderCompany;
                    intrasitDb.SubItem_Name = item.SubItemName;
                    intrasitDb.SubItem_Code = item.subItemCodeVal;
                    intrasitDb.Material_Description = item.MaterialDescription;
                    intrasitDb.Unit = item.Unit;
                    intrasitDb.Amt = item.Amt;
                    intrasitDb.Qty = item.Qty;
                    intrasitDb.Item_Code = item.ItemCode;
                    intrasitDb.Login_Branch = branch.BranchCode;
                    _IntrasitHelper.CreateNewIntrasit(intrasitDb);
                }
                return Json(new { success = true, message = "Saved Successfully" });
                // return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Not Saved Successfully" });
                //return View(intrasitc);
            }
        }

        [HttpPost]
        public IActionResult OnPostMyUploader(IFormFile importFile)
        {
            if (importFile == null) return Json(new { Status = 0, Message = "No File Selected" });

            try
            {

                //Getting FileName
                var fileName = Path.GetFileName(importFile.FileName);
                //Getting file Extension
                var fileExtension = Path.GetExtension(fileName);
                // concatenating  FileName + FileExtension
                var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);
                DataSet ds = new DataSet();
                using (var target = new MemoryStream())
                {
                    importFile.CopyTo(target);
                    using (var reader = ExcelReaderFactory.CreateReader(target))
                    {
                        ds = reader.AsDataSet();
                    }
                    //var fileData = GetDataFromCSVFile(ds);
                    GetDataFromCSVFile(ds);
                }


                //var dtEmployee = fileData.ToDataTable();
                //var tblEmployeeParameter = new SqlParameter("tblEmployeeTableType", SqlDbType.Structured)
                //{
                //    TypeName = "dbo.tblTypeEmployee",
                //    Value = dtEmployee
                //};
                //await _dbContext.Database.ExecuteSqlCommandAsync("EXEC spBulkImportEmployee @tblEmployeeTableType", tblEmployeeParameter);
                return Json(new { Status = 1, Message = "File Imported Successfully " });
            }
            catch (Exception ex)
            {
                return Json(new { Status = 0, Message = ex.Message });
            }
        }
        private void GetDataFromCSVFile(DataSet ds)
        {

            try
            {
                DataTable dt = new DataTable();
                dt.Columns.Add("LoginBranch", typeof(string));
                dt.Columns.Add("SenderCompany", typeof(string));
                dt.Columns.Add("Branch", typeof(string));
                dt.Columns.Add("PurchaseOrder", typeof(string));
                dt.Columns.Add("ItemCode", typeof(string));
                dt.Columns.Add("SubItemCode", typeof(string));
                dt.Columns.Add("SubItemName", typeof(string));
                dt.Columns.Add("MaterialDescription", typeof(string));
                dt.Columns.Add("Qty", typeof(string));
                dt.Columns.Add("Unit", typeof(string));
                dt.Columns.Add("Amt", typeof(string));
                DataTable dt2 = ds.Tables["Sheet1"];

                foreach (DataRow dr in dt2.Rows)
                {
                    dt.Rows.Add(dr.ItemArray);
                }
                dt.Rows[0].Delete();
                dt.AcceptChanges(); dt2.AcceptChanges();
                dt.Columns["LoginBranch"].ColumnName = "LoginBranch";
                dt.Columns["SenderCompany"].ColumnName = "SenderCompany";
                dt.Columns["Branch"].ColumnName = "Branch";
                dt.Columns["PurchaseOrder"].ColumnName = "PurchaseOrder";
                dt.Columns["ItemCode"].ColumnName = "ItemCode";
                dt.Columns["SubItemCode"].ColumnName = "SubItemCode";
                dt.Columns["SubItemName"].ColumnName = "SubItemName";
                dt.Columns["MaterialDescription"].ColumnName = "MaterialDescription";
                dt.Columns["Qty"].ColumnName = "Qty";
                dt.Columns["Unit"].ColumnName = "Unit";
                dt.Columns["Amt"].ColumnName = "Amt";
                _IntrasitHelper.blukUpload(dt);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpGet]
        public JsonResult GetSubItem(int subItemId)
        {
            var data = _IntrasitHelper.GetSubItem(subItemId);
            return Json(data);
        }//GetMaterialDesc

WMSApp/WMSWebApp/Views/Intrasit/Create.cshtml
@model WMSWebApp.ViewModels.IntransitViewModel

@{
    ViewData["Title"] = "Add New Intrasit";
    Layout = "../Shared/_Layout.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Intrasit Process</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Process</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Intrasit Process</h3>

                    </div>
                    @* <form>*@
                    <div class="card-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class=row>
                            <div class=" col-md-6">

                                <div class="form-group">
                                    <label asp-for="intrasitc.PurchaseOrder"></label>
                                    <input asp-for="intrasitc.PurchaseOrder" class="form-control "  id="txtPurchaseOrder" />
                                </div>
                                <span asp-validation-for="intrasitc.PurchaseOrder" class="text-danger"></span>
                            </div>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.SenderCompany"></label>
                                    <select asp-for="CId" class="form-control " asp-items="@(new SelectList(@ViewBag.ListofCompany,"Id", "CompanyName"))">
                                    </select>
                                </div>
                                <span asp-validation-for="intrasitc.SenderCompany" class="text-danger"></span>
                            </div>
                        </div>
                        <div class=row>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.Branch"></label>
                                    <select asp-for="BId" class="form-control " asp-items="@(new SelectList(@ViewBag.listBranch,"Id", "BranchName"))">
                                    </select>
                                </div>
                                <span asp-validation-for="intrasitc.Branch" class="text-danger"></span>
                            </div>
                            <div class=" col-md-6">

                                <div class="form-group">
                                    <label asp-for="intrasitc.ItemCode"></label>

                                    <select asp-for="ItId" class="form-control " asp-items="@(new SelectList(@ViewBag.listItem,"Id", "ItemName"))">
                                    </select>
                                </div>
                                <span asp-validation-for="intrasitc.ItemCode" class="text-danger"></span>
                            </div>
                        </div>

                        <div class=row>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.SubItemName"></label>

                                    <select asp-for="SubItemId" class="form-control " id="subItemId">
                                        <option value="">Select</option>
                                    </select>
                                </div>
                                <span asp-validation-for="intrasitc.SubItemName" class="text-danger"></span>
                            </div>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.MaterialDescription"></label>
                                    <input asp-for="intrasitc.MaterialDescription" class="form-control"  id="txtMDesc" readonly/>
                                </div>
                             
                            </div>
                        </div>
                        <div class=row>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.Qty"></label>
                                    <input asp-for="intrasitc.Qty" class="form-control" id="txtqty" />
                                </div>
                                @*<span asp-validation-for="EmailIdHO" class="text-danger"></span>*@
                            </div>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.Unit"></label>
                                    <input asp-for="intrasitc.Unit" class="form-control" id="txtunit" name="unit" />
                                </div>
                                @*  <span asp-validation-for="SpaceSizeFormat" class="text-danger"></span>*@
                            </div>
                        </div>
                        <div class=row>
                            <div class=" col-md-6">
                                <div class="form-group">
                                    <label asp-for="intrasitc.Amt"></label>
                                    <input asp-for="intrasitc.Amt" class="form-control"  id="txtAmt" name="amt" />
                                </div>

                            </div>

                        </div>
                    </div>

                    <div class="card-footer">
                        <input type="submit" value="Create" class="btn btn-primary" id="btnaddRow" />
                        <a asp-action="Index" class="btn btn-primary float-right">Back to List</a>
                    </div>
                    @* </form>*@
                </div>
            </div>
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Upload Bulk</h3>

                    </div>
                    @* <form id="fileUploadForm" method="post" enctype="multipart/form-data" asp-controller="Intrasit" asp-action="OnPostMyUploader">*@
                    <div class="card-body">
                        @*<div class="form-group">
                            <label for="exampleInputFile">Upload file:</label>
                            <div class="input-group">
                            <div class="custom-file">
                            <input type="file" id="uploadFile" name="uploadFile" />
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                            </div>
                            <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                            </div>
                            </div>
                            </div>*@
                        <partial name="_InTransitList.cshtml" />
                    </div>
                    <div class="card-footer">
                        <button type="submit" id="btnsubmit" value="Upload" class="btn btn-primary"><i class="fa fa-cloud-upload" aria-hidden="true"></i> Submit</button>
                    </div>




                    @*   </form>*@
                </div>
            </div>
        </div>
    </div>
</section>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<script src="~/js/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="~/js/Intrasit.js"></script>
}

WMSApp/WMSWebApp/Views/Intrasit/Index.cshtml
@model IEnumerable<WMSWebApp.ViewModels.Intrasitc>

@{
    ViewData["Title"] = "Index";
}
@* Delete this below CSS File after revamping is done. *@

<link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Intrasit List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Master</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Upload Bulk</h3>
                    </div>
                    <form id="fileUploadForm" method="post" enctype="multipart/form-data" asp-controller="Intrasit" asp-action="OnPostMyUploader">
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputFile">Upload file:</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" id="uploadFile" name="uploadFile" />
                                        @* <label class="custom-file-label" for="exampleInputFile">Choose file</label>*@
                                        @* <input type="submit" value="Upload" />*@
                                    </div>

                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button type="submit" value="Upload" class="btn btn-primary"><i class="fa fa-cloud-upload" aria-hidden="true"></i> Upload</button>
                        </div>




                    </form>
                </div>
            </div>
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <a asp-action="Create" class="btn btn-primary">Create New</a>
                        <a asp-action="DownloadFile" class="btn btn-primary">Download</a>
                        <div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card-body table-responsive p-0" style="height: 300px;">
                        <table class="table table-head-fixed text-nowrap" id="tblIntrasit">
                            <thead>
                                <tr>
                                    @* <th>
                                        @Html.DisplayNameFor(model => model.Id)
                                        </th>*@
                                    <th>
                                        @Html.DisplayNameFor(model => model.PurchaseOrder)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Branch)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ItemCode)
                                    </th>
                                      <th>
                                        @Html.DisplayNameFor(model => model.SubItemCode)
                                        </th>
                                   @* <th>
                                        @Html.DisplayNameFor(model => model.SubItemName)
                                    </th>*@
                                    <th>
                                        @Html.DisplayNameFor(model => model.MaterialDescription)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Qty)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Unit)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Amt)
                                    </th>
                                     <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PurchaseOrder)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Branch)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.ItemCode)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SubItemCode)
                                        </td>

                                        <td>
                                            @Html.DisplayFor(modelItem => item.MaterialDescription)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Qty)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Unit)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Amt)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) 
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts{
<!--Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
<script>
        $(document).ready(function() {
        let table = $('#tblIntrasit').DataTable( {
                
            });
         });
      $("#fileUploadForm").submit(function(e) {
            e.preventDefault();
            //debugger;
            var file = $('#uploadFile').val();
            if (!(/\.(xlsx|xls|xlsm)$/i).test(file)) {
                alert('Please upload valid excel file .xlsx, .xlsm, .xls only.');
                $("#uploadFile").val('');
            } else {
                var data = new FormData();
                data.append("importFile", $("#uploadFile")[0].files[0]);
                $.ajax({
                    type: 'post',
                    url: "/Intrasit/OnPostMyUploader",
                    data: data,
                    processData: false,
                    contentType: false
                }).done(function(result) {
                    if (result.Status === 1) {
                        alert(result.Message);
                        location.reload();
                    }
                    else {
                        alert(result.Message);
                    }
                });
            }
        });
</script>
	}

WMSApp/WMSWebApp/Views/Intrasit/_InTransitList.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@model WMSWebApp.ViewModels.IntransitViewModel;

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table id="tblJobBoard" class="table table-bordered compactTable text-center" style="width:100%">
                <thead class="bg-light">
                    <tr>
                        @*<td>Id</td>*@
                        <td>PurchaseOrder</td>
                        <td>Sender Company</td>
                        <td>Sender Branch</td>
                        <td>Item Code</td>
                        <td>SubItem Name</td>
                        <td>Material Description</td>
                        <td>QTY</td>
                        <td>Unit</td>
                        <td>Amt</td>
                    </tr>
                </thead>
                <tbody>
                    @*	@for (int i = 0; i < Model.intrasitcList.Count; i++)
                        {
                        <tr>
                        <td>@Model.intrasitcList[i].Branch</td>
                        <td>@Model.intrasitcList[i].PurchaseOrder</td>
                        <td>@Model.intrasitcList[i].ItemCode</td>
                        <td>@Model.intrasitcList[i].SenderCompany</td>
                        <td>@Model.intrasitcList[i].SubItemName</td>
                        <td>@Model.intrasitcList[i].MaterialDescription</td>
                        <td>@Model.intrasitcList[i].Qty</td>
                        <td>@Model.intrasitcList[i].Amt</td>
                        <td>
                        </tr>
                        }*@
                </tbody>
            </table>
        </div>

    </div>
</div>

<script>
    $(document).ready(function () {
        $("#tblJobBoard").DataTable({
           
         });

    });
</script>