WMSApp/WMSWebApp/ViewModels/Branch.cs
using System.ComponentModel.DataAnnotations;
using Domain.Model.CompanyMaster;
using System.Collections.Generic;
using WMS.Data;

namespace WMSWebApp.ViewModels
{
    public class Branch
    {

        [Display(Name = "Screen Code")]
        public string ScreenCode { get; set; }
        [Display(Name = "Branch Code")]
        public string BranchCode { get; set; }

        [Display(Name = "Branch Name")]
        public string BranchName { get; set; }
        [DataType(DataType.MultilineText)]

        [Display(Name = "Company Name")]
        public int CompanyId { get; set; }
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        [DataType(DataType.MultilineText)]
        public string Location { get; set; }

        [Display(Name = "Branch Contact Person")]
        public string ContactPersonBranch { get; set; }
        [DataType(DataType.MultilineText)]
        [Required]
        [Phone]
        [Display(Name = "Branch Contact Number")]
        public string ContactNumberBranch { get; set; }
        [Required]
        [EmailAddress]
        [Display(Name = "Branch Email ID")]
        public string EmailIdBranch { get; set; }

        [Display(Name = "Associated Employee")]
        public string AssociatedEmployee { get; set; }

        [Display(Name = "Warehouse Name")]
        public int WarehouseId { get; set; }

        public List<Company> Companies { get; set; }

        public List<ApplicationUser> Users { get; set; }

    }
}

WMSApp/WMSWebApp/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using Application.Services;
using AutoMapper;
using DatabaseLibrary.SQL;
using Domain.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WMS.Data;
using WMSWebApp.ViewModels;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Application.Services.Master;
using Domain.Model.Masters;
using Application.Services.WarehouseMaster;
using WMS.Web.Framework.Infrastructure.Extentsion;
using Microsoft.Extensions.Configuration;
using System.Net.Http;
using Newtonsoft.Json;
using Application.Services.Security;

namespace WMSWebApp.Controllers
{
    [Authorize]
    public class BranchController : BaseAdminController
    {
        private readonly IBranchHelper _BranchHelper;
        private readonly IMapper _mapper;
        private readonly ICompanyHelper _companyService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserProfileService _userProfileService;
        private readonly IWarehouseService _warehouseService;
        private readonly IConfiguration Configuration;
        private readonly IPermissionMasterService _permissionMasterService;

        public BranchController(IBranchHelper BranchHelper, IMapper mapper, ICompanyHelper companyService, UserManager<ApplicationUser> userManager,
            IUserProfileService userProfileService, IWarehouseService warehouseService, IConfiguration _configuration, IPermissionMasterService permissionMasterService)
        {
            _BranchHelper = BranchHelper;
            _mapper = mapper;
            _companyService = companyService;
            _userManager = userManager;
            _userProfileService = userProfileService;
            _warehouseService = warehouseService;
            Configuration = _configuration;
            _permissionMasterService = permissionMasterService;
        }



        public ActionResult Index()
        {
            if (!_permissionMasterService.Authorize(StandardPermissionProvider.Branch, PermissionType.View).Result)
            {
                return AccessDeniedView();
            }
            return View();
        }


        [HttpPost]
        public virtual IActionResult List(DataSourceRequest request)
        {
            var branches = _BranchHelper.GetAllBranches(request.Page - 1, request.PageSize);
            var gridData = new DataSourceResult
            {
                Data = branches.Select(x =>
                {
                    BranchModel m = new BranchModel();
                    m = _mapper.Map<BranchModel>(x);
                    var user = _userProfileService.GetByUserId(x.AssociatedEmployee);
                    if (user != null)
                    {
                        m.UserName = $"{user.FirstName} {user.LastName}";
                    }
                    var warehouse = x.BranchWiseWarehouses.Select(x => x.Warehouse);

                    if (warehouse.Any())
                    {
                        m.Werehouse = string.Join(',', warehouse.Select(x => x.WarehouseName).ToArray());
                    }
                    var comp = _companyService.GetCompanyById(x.CompanyId);
                    if (comp != null)
                    {
                        m.CompanyName = comp.CompanyName;
                    }
                    return m;
                }),
                Total = branches.TotalCount
            };
            return Json(gridData);
        }

        public ActionResult Details(int id)
        {
            var B = new Branch()
            {
                BranchName = "Test",
                BranchCode = "Test",
                CompanyId = 1,
                Address = "Test",
                Location = "Location",
                ContactPersonBranch = "ContactPersonBranch",
                ContactNumberBranch = "ContactNumberBranch"
            ,
                EmailIdBranch = "EmailIdBranch",
                AssociatedEmployee = "AssociatedEmployee ",
                //WarehouseId = 1,
            };
            return View(B);
        }
        // GET: CompaniesController/Create
        public ActionResult Create()
        {
            if (!_permissionMasterService.Authorize(StandardPermissionProvider.Branch, PermissionType.Add).Result)
            {
                return AccessDeniedView();
            }
            BranchModel model = new BranchModel();
            var comp = _companyService.GetAllCompanies();
            var companies = _mapper.Map<List<Company>>(comp);
            model.Companies = companies;
            var users = PrepareUserList(_userProfileService.GetAllProfile("").ToList());
            model.Users = users;
            model.Warehouses = _warehouseService.GetAllWarehouse().ToList();
            Root districtslist = new Root();
            HttpClient client = new HttpClient();
            string apiUrl = Configuration.GetValue<string>("districtUrl");
            HttpResponseMessage response = client.GetAsync(apiUrl).Result;
            if (response.IsSuccessStatusCode)
            {
                districtslist = JsonConvert.DeserializeObject<Root>(response.Content.ReadAsStringAsync().Result);
            }
            ViewBag.districts = districtslist.districts;
            return View(model);
        }

        // POST: BranchController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BranchModel c, IFormCollection collection)
        {
            try
            {
                var branch = _mapper.Map<Branch>(c);
                foreach (var item in c.WarehouseId)
                {
                    var mapping = new BranchWiseWarehouse()
                    {
                        WarehouseId = item,
                        Branch = branch,



                    };
                    branch.BranchWiseWarehouses.Add(mapping);
                }
                _BranchHelper.Insert(branch);
                SuccessNotification("Branch created successfully!.");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(c);
            }
        }

        // GET: CompaniesController/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_permissionMasterService.Authorize(StandardPermissionProvider.Company, PermissionType.Edit).Result)
            {
                return AccessDeniedView();
            }
            var model = new BranchModel();
            try
            {
                var data = _BranchHelper.GetById(id);
                model = _mapper.Map<BranchModel>(data);
                var comp = _companyService.GetAllCompanies();
                var companies = _mapper.Map<List<Company>>(comp);
                model.Companies = companies;
                var users = PrepareUserList(_userProfileService.GetAllProfile("").ToList());
                model.Users = users;
                model.Warehouses = _warehouseService.GetAllWarehouse().ToList();
                model.WarehouseId = data.BranchWiseWarehouses.Select(x => x.WarehouseId).ToList();
            }
            catch (Exception)
            {
                throw;
            }
            return View(model);
        }
        // POST: CompaniesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, BranchModel c, IFormCollection collection)
        {
            var branch = _BranchHelper.GetById(c.Id);
            branch = _mapper.Map<BranchModel, Branch>(c, branch);

           
            _BranchHelper.Update(branch);
            SuccessNotification("Branch updated successfully!.");
            return RedirectToAction(nameof(Index));
        }
        // GET: CompaniesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BranchController/Delete/5
        // POST: CompaniesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [NonAction]
        protected List<UserProfileModel> PrepareUserList(List<UserProfile> users)
        {
            List<UserProfileModel> list = new List<UserProfileModel>();
            foreach (var item in users)
            {
                UserProfileModel model = new UserProfileModel();
                model.UserId = item.UserId;
                model.Name = $"{item.FirstName} {item.LastName}";
                list.Add(model);
            }
            return list;
        }

        protected void PrepareBrachCreate(Branch branch, BranchModel model)
        {
            branch.Address = model.Address;
            branch.BranchCode = model.BranchCode;
            branch.BranchName = model.BranchName;
            branch.CompanyId = model.CompanyId;
            branch.EmailIdBranch = model.EmailIdBranch;

        }
    }
}

WMSApp/WMSWebApp/Views/Branch/Create.cshtml
@model WMSWebApp.ViewModels.BranchModel

@{
    ViewData["Title"] = "Create";
}
@section Style{
<!-- Select2 -->
<link rel="stylesheet" href="~/lib/plugins/select2/css/select2.min.css">
<link rel="stylesheet" href="~/lib/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">

}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Create New Branch</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Master</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create New Branch</h3>

                    </div>
                    <form asp-action="Create">


                        <div class="card-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="row">
                                @*  <div class="col-md-6">
                                    <div class="form-group">
                                    <label asp-for="ScreenCode">Screen Code</label>
                                    <input type="text" asp-for="ScreenCode" id="ScreenCode" autocomplete="off" class="form-control">
                                    <span asp-validation-for="ScreenCode" class="text-danger"></span>
                                    </div>
                                    </div>*@
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="BranchCode">Branch Code</label>
                                        <input type="text" asp-for="BranchCode" id="BranchCode" autocomplete="off" class="form-control">
                                        <span asp-validation-for="BranchCode" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="BranchName">Branch Name</label>
                                        <input type="text" asp-for="BranchName" id="BranchName" autocomplete="BranchName" class="form-control">
                                        <span asp-validation-for="BranchName" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>




                            <div class=row>
                                <div class=" col-md-6">
                                    <div class="form-group">
                                        <label asp-for="EmailIdBranch"></label>
                                        <input asp-for="EmailIdBranch" class="form-control" />
                                    </div>
                                    <span asp-validation-for="EmailIdBranch" class="text-danger"></span>
                                </div>
                                 <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="CompanyId">Compnay Name</label>
                                        <select asp-for="CompanyId" id="CompanyName" autocomplete="CompanyName" class="form-control select2" asp-items="@(new SelectList(Model.Companies,"Id","CompanyName"))"></select>
                                        <span asp-validation-for="CompanyId" class="text-danger"></span>
                                    </div>
                                </div>
                               @* <div class="col-md-6">
                                    <div class="form-group ">
                                        <label asp-for="AssociatedEmployee"></label>
                                        <select asp-for="AssociatedEmployee" class="form-control select2" asp-items="@(new SelectList(Model.Users,"UserId","Name"))">
                                        </select>
                                    </div>
                                    <span asp-validation-for="AssociatedEmployee" class="text-danger"></span>
                                </div>*@
                            </div>
                         

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Address">Address</label>
                                        <input type="text" asp-for="Address" id="Address" autocomplete="Address" class="form-control">
                                        <span asp-validation-for="Address" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="Location">Location</label>
                                        @* <input type="text" asp-for="Location" id="Location" autocomplete="Location" class="form-control">*@
                                        <select class="form-control" id="ddllocation" asp-items="@(new SelectList(@ViewBag.districts,"district_id", "district_name"))">
                                        </select>
                                        <input asp-for="Location" type="hidden" />
                                        <span asp-validation-for="Location" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="ContactPersonBranch">Contact Person Branch</label>
                                        <input type="text" asp-for="ContactPersonBranch" id="ContactPersonBranch" autocomplete="off" class="form-control">
                                        <span asp-validation-for="ContactPersonBranch" class="text-danger"></span>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label asp-for="ContactNumberBranch">Contact Number Branch</label>
                                        <input type="text" asp-for="ContactNumberBranch" autocomplete="off" class="form-control" id="txtcontactno">
                                        <span asp-validation-for="ContactNumberBranch" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>
                            @*<div class="row">
                                <div class="col-md-6">
                                <div class="form-group">
                                <label asp-for="EmailIdBranch">Email Id Branch</label>
                                <input type="text" asp-for="EmailIdBranch" id="EmailIdBranch" autocomplete="off" class="form-control">
                                <span asp-validation-for="EmailIdBranch" class="text-danger"></span>
                                </div>
                                </div>
                                <div class="col-md-6">
                                <div class="form-group">
                                <label asp-for="AssociatedEmployee">Associated Employee</label>
                                <input type="text" asp-for="AssociatedEmployee" id="AssociatedEmployee" autocomplete="off" class="form-control">
                                <span asp-validation-for="AssociatedEmployee" class="text-danger"></span>
                                </div>
                                </div>
                                </div>*@


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group ">
                                        <label asp-for="WarehouseId">Warehouse Name</label>
                                        <div class="select2-purple">
                                            <select asp-for="WarehouseId" data-placeholder="Select a Warehouse" multiple="multiple" data-dropdown-css-class="select2-purple" class="select2 multiselect" asp-items="@(new SelectList(Model.Warehouses,"Id","WarehouseName"))" style="width: 100%;"></select>
                                        </div>

                                        <span asp-validation-for="WarehouseId" class="text-danger"></span>
                                    </div>
                                </div>
                            </div>







                        </div>
                        <div class="card-footer">
                            <button type="submit" value="Create" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
<!-- Select2 -->
<script src="~/lib/plugins/select2/js/select2.full.min.js"></script>
<script>
    $(function() {
        $('.select2').select2({
            theme: 'bootstrap4'
        })
        $('.multiselect').select2()
    });
</script>
<script type="text/javascript">
    //    $("#txtcontactno").keydown(function(event) {
    //  k = event.which;
    //  if ((k >= 96 && k <= 105) || k == 8) {
    //    if ($(this).val().length == 10) {
    //      if (k == 8) {
    //        return true;
    //      } else {
    //        event.preventDefault();
    //        return false;

    //      }
    //    }
    //  } else {
    //    event.preventDefault();
    //    return false;
    //  }

    //});
      $('#ddllocation').change(function() {debugger;
        $('#Location').val($("#ddllocation option:selected").text());
    });

</script>
    }

WMSApp/WMSWebApp/Views/Branch/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Style{
<link href="~/lib/kendoUi/2021/styles/kendo.common.min.css" rel="stylesheet" />
<link href="~/lib/kendoUi/2021/styles/kendo.rtl.min.css" rel="stylesheet" />
<link href="~/lib/kendoUi/2021/styles/kendo.default.min.css" rel="stylesheet" />
<link href="~/lib/kendoUi/2021/styles/kendo.default.mobile.min.css" rel="stylesheet" />


}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Branch List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Master</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Branchs</h3>

                        @*<div class="card-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                                <div class="input-group-append">
                                    <button type="submit" class="btn btn-default">
                                        <i class="fas fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>*@
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div id="branch-grid">
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
        </div>
    </div>
</section>


@section Scripts{
   <environment include="Development">
    <script src="~/lib/kendoUi/2021/js/kendo.all.min.js"></script>
    <script src="~/lib/kendoUi/2021/js/jszip.min.js"></script>
    <script src="~/js/common.js"></script>
    
</environment>
<environment exclude="Development">
    <script src="~/lib/kendoUi/2021/js/kendo.all.min.js"></script>
    <script src="~/lib/kendoUi/2021/js/jszip.min.js"></script>
    <script src="~/js/common.min.js"></script>
    

</environment>

    <script>
        function additionalData() {
            var data = {
                //userid: $("#hdnAgentID").val(),
                //pnr: $("#pnr").val(),
                //bookingRefNo: $("#bookingRefNo").val(),
                //email: $("#email").val(),
                //mobile: $("#mobile").val(),
                //fromDate: $("#fromDate").val(),
                //toDate: $("#toDate").val(),
                //apisource:$("#apisource").val()
            }
            addAntiForgeryToken(data);
            return data;
        }

        var initialLoad = true;
        $("#branch-grid").kendoGrid({

            toolbar: ["excel"],
            excel: {
                fileName: "branch Export.xlsx",
                proxyURL: "@Html.Raw(Url.Action("List", "Branch"))",
                filterable: true
            },
            dataSource: {

                transport: {
                    read: {
                        url: "@Html.Raw(Url.Action("List", "Branch"))",
                        type: "POST",
                        dataType: "json",
                        data: additionalData,
                        complete: function(result) {
                            console.log("Remote built-in transport", result);
                            if (result.status == 401) {
                                document.location.href = "@Html.Raw(Url.Action("Index", "AccessDenied"))";
                            }
                        }

                    }
                },
                schema: {
                    data: "Data",
                    total: "Total",
                    errors: "Errors"
                },
                error: function(e) {
                    //display_kendoui_grid_error(e);
                    // Cancel the changes
                    console.log(e)
                    this.cancelChanges();
                },
                pageSize: 20,
                sortable: true,
                serverPaging: true,
                serverSorting: true,
                requestStart: function() {
                    if (initialLoad) //<-- if it's the initial load, manually start the spinner
                        kendo.ui.progress($("#branch-grid"), true);
                },
                requestEnd: function() {
                    if (initialLoad)
                        kendo.ui.progress($("#branch-grid"), false);
                    initialLoad = false; //<-- make sure the spinner doesn't fire again (that would produce two spinners instead of one)

                },

            },
            pageable: {
                refresh: true,
                pageSizes: true
            },
            excel: {
                allPages: true
            },
            scrollable: false,
            columns: [{
                field: "Id",
                title: "ID",
                width: 50
            },
            {
                field: "BranchCode",
                title: "BranchCode",
                width: 50
            },

            {
                field: "BranchName",
                title: "BranchName",
                width: 300
            },
            {
                field: "CompanyName",
                title: "CompanyName",
                encoded: false,
                width: 300
            },
            {
                field: "Werehouse",
                title: "Werehouse",
                width: 300
            },
            {
                field: "UserName",
                title: "UserName",
                width: 120
            },
           
           
           
          
            {
                field: "EmailIdBranch",
                title: "EmailId",
                width: 50
            },

            {
                field: "Address",
                title: "Address",
                width: 300
            },
            {
                field: "Location",
                title: "Location",
                width: 50
            },
           
            {
                field: "ContactNumberBranch",
                title: "Contact",
                width: 50
            },
           

            {
                title: "Action",
                headerAttributes: { style: "text-align:center" },
                template: '<a href="@(Url.Action("Edit","Branch"))/?id=#=Id#" class="btn btn-primary">Edit</a>',
                width: 100
            },
            //{
            //    title: "Action",
            //    headerAttributes: { style: "text-align:center" },
            //    attributes: { style: "text-align:center" },
            //    template: '<a href="@(Url.Action("CancelTicket","AgentBooking"))/?id=#=ID#" class="btn btn-danger">Cancel</a>',
            //    width: 100
            //},
            //{
            //    title: "Action",
            //    headerAttributes: { style: "text-align:center" },
            //    attributes: { style: "text-align:center" },
            //    template: '#if(BookingStatus=="PENDING"){#<a href="@(Url.Action("RejectBooking","AgentBooking"))/?id=#=ID#" class="btn btn-danger">Reject</a>#}#',
            //    width: 100
            //},

            ],

        });
    </script>
	}