WMSApp/WMSWebApp/ViewModels/GRN/CreateModel.cs
using System.Collections.Generic;
using Domain.Model.Masters;
namespace WMSWebApp.ViewModels.GRN
{
    public class CreateModel
    {

        public int ItemId { get; set; }
        public int zone { get; set; }
        public int WarehouseId { get; set; }
        public int Warea { get; set; }
        public string Remark { get; set; }
        public string wcode { get; set; }
        public string zcode { get; set; }
        public string acode { get; set; }
        public string Ponumber { get; set; }
        public string invoice { get; set; }
        public string GRNNumberOfSAP { get; set; }
        public string IRN { get; set; }

        public bool AllowGRN { get; set; }


        public List<VendorVehicle> Vehicles { get; set; }

    }
}

WMSApp/WMSWebApp/ViewModels/GRN/GRNListReportModel.cs
using System;
namespace WMSWebApp.ViewModels.GRN
{
	public class GRNListReportModel
	{
        public int Id { get; set; }
        public string PONo { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime InvoiceDate { get; set; }
        public string BranchCode { get; set; }
        public string SenderCompany { get; set; }
        public string Branch { get; set; }
        public string GRNNumberOfSAP { get; set; }
        public string IRN { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/GRN/GRNModel.cs
using System;
using System.Collections.Generic;
namespace WMSWebApp.ViewModels.GRN
{
    public class GRNModel
    {
        public string PONo { get; set; }
        public string InvoiceNo { get; set; }
        public DateTime InvoiceDate { get; set; } = new DateTime();
        public string BranchCode { get; set; }
        public string SenderCompany { get; set; }
        public List<GrnItems> Items { get; set; }
    }
    public class GrnItems
    {
        public int GRNId { get; set; }
        public string ItemCode { get; set; }
        public string SubItemCode { get; set; }
        public string SubItemName { get; set; }
        public string MaterialDescription { get; set; }
        public int Qty { get; set; }
        public string Unit { get; set; }
        public decimal Amount { get; set; }
        public int AreaId { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/GRN/GrnItemListModel.cs
namespace WMSWebApp.ViewModels.GRN
{
    public class GrnItemListModel
    {
        public int Id { get; set; }
        public string POId { get; set; }

        public string ItemCode { get; set; }
        public string SubItemCode { get; set; }
        public string SubItemName { get; set; }
        public string MaterialDescription { get; set; }
        public int Qty { get; set; }
        public string Unit { get; set; }
        public decimal Amount { get; set; }
        public int AreaId { get; set; }
        public string Location { get; set; }
        public int InventoryId { get; set; }

        public string DockType { get; set; }
    }
}

WMSApp/WMSWebApp/ViewModels/GRN/GrnListModel.cs
namespace WMSWebApp.ViewModels.GRN
{
    public class GrnListModel
    {
        public int GRNId { get; set; }
        public string PoNumber { get; set; }

    }
}

WMSApp/WMSWebApp/ViewModels/GRN/SubItemLocationModel.cs
namespace WMSWebApp.ViewModels.GRN
{
    public class SubItemLocationModel
    {
        public int WareHouseId { get; set; }
        public int WareHouseAreaId { get; set; }
        public int LocationId { get; set; }

    }
}

WMSApp/WMSWebApp/Controllers/GrnController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Domain.Model;
using Application.Services.GRN;
using WMS.Data;
using System.Linq;
using System.Threading.Tasks;
using WMSWebApp.ViewModels;
using AutoMapper;
using System.Collections.Generic;
using WMSWebApp.ViewModels.GRN;
using WMS.Web.Framework.Infrastructure.Extentsion;
using Application.Services.WarehouseMaster;
using System;
using Domain.Model.GRN;
using Application.Services.StockMgnt;
using Domain.Model.StockManagement;
using Application.Services.Master;
using Application.Services;
using Sentry;

namespace WMSWebApp.Controllers
{
    [Authorize]
    public class GrnController : BaseAdminController
    {
        #region Fields
        private readonly IIntrasitService _intrasitService;
        private readonly IWorkContext _workContext;
        private readonly IMapper _mapper;
        private readonly IWarehouseService _warehouseService;
        private readonly IGoodReceivedNoteMasterService _goodReceivedNoteMasterService;
        private readonly IItemStockService _itemStockService;
        private readonly IVenderVehicleService _venderVehicleService;
        private readonly IBranchHelper _branchService;
        private readonly ISubItemWarehouseMappingService _subItemWarehouseMappingService;
        #endregion

        #region Ctor
        public GrnController(IIntrasitService intrasitService, IWorkContext workContext, IMapper mapper, IWarehouseService warehouseService, IGoodReceivedNoteMasterService goodReceivedNoteMasterService, IItemStockService itemStockService, IVenderVehicleService venderVehicleService, IBranchHelper branchService, ISubItemWarehouseMappingService subItemWarehouseMappingService)
        {
            _intrasitService = intrasitService;
            _workContext = workContext;
            _mapper = mapper;
            _warehouseService = warehouseService;
            _goodReceivedNoteMasterService = goodReceivedNoteMasterService;
            _itemStockService = itemStockService;
            _venderVehicleService = venderVehicleService;
            _branchService = branchService;
            _subItemWarehouseMappingService = subItemWarehouseMappingService;
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            CreateModel model = new CreateModel();
            model.Vehicles = _venderVehicleService.VendorVehicles().ToList();

            //var branch = await _workContext.GetCurrentBranch();
            //List<WarehouseModel> warehouseModel = new List<WarehouseModel>();
            //foreach (var item in branch.BranchWiseWarehouses)
            //{
            //    WarehouseModel warehouse = new WarehouseModel();
            //    warehouse.WarehouseName = item.Warehouse.WarehouseName;
            //    warehouse.WarehouseCode = item.Warehouse.WarehouseCode;
            //    warehouse.Id = item.Warehouse.Id;
            //    List<WarehouseZoneAreaModel> ZoneList = new List<WarehouseZoneAreaModel>();
            //    foreach (var zone in item.Warehouse.WarehouseZones)
            //    {
            //        var Zone = new WarehouseZoneAreaModel();
            //        Zone.ZoneName = zone.ZoneName;
            //        Zone.ZoneCode = zone.ZoneCode;
            //        ZoneList.Add(Zone);

            //    }
            //    warehouse.ZoneAreaList = ZoneList;
            //    warehouseModel.Add(warehouse);
            //}
            //model.Warehouse = warehouseModel;

            return View(model);
        }

        [HttpGet]
        public virtual async Task<IActionResult> PendingPO(string term)
        {
            var branch = await _workContext.GetCurrentBranch();
            term = (term == null || term == "") ? "0" : term;
            var intrasitData = _intrasitService.GetPendingPO(branch.BranchCode, term, 0, int.MaxValue).ToList().GetUniqePo();
            return Json(intrasitData);

        }

        [HttpPost]
        public virtual async Task<IActionResult> PODetails(string pono)
        {
            SentrySdk.CaptureMessage("PODetails() ");
            var branch = await _workContext.GetCurrentBranch();
            SentrySdk.CaptureMessage("PODetails() "+ branch.Id);
            var intrasitData = _intrasitService.GetPendingPO(branch.BranchCode, pono, 0, int.MaxValue);
            int id = 1;
            var data = new DataSourceResult()
            {
                Data = intrasitData.Select(x =>
                {
                    var m = new Intrasitc();

                    m.Id = x.Id;
                    m.LoginBranch = x.Login_Branch;
                    m.SenderCompany = x.Sender_Company;
                    m.Branch = x.Sender_Branch;
                    m.PurchaseOrder = x.PurchaseOrder;
                    m.ItemCode = x.Item_Code;
                    m.SubItemCode = x.SubItem_Code;
                    m.SubItemName = x.SubItem_Name;
                    m.MaterialDescription = x.Material_Description;
                    m.Qty = x.Qty;
                    m.Unit = x.Unit;
                    m.Amt = x.Amt;
                    m.ETA = x.ETA;
                    m.Sno = id;
                    m.AllowGRN = false;
                    id++;
                    return m;
                }),
                Total = intrasitData.TotalCount
            };

            return Json(data);
        }

        [HttpGet]
        public virtual IActionResult GetItemDetails(int id)
        {
            var x = _intrasitService.GetById(id);
            var m = new Intrasitc();
            m.Id = x.Id;
            m.LoginBranch = x.Login_Branch;
            m.SenderCompany = x.Sender_Company;
            m.Branch = x.Sender_Branch;
            m.PurchaseOrder = x.PurchaseOrder;
            m.ItemCode = x.Item_Code;
            m.SubItemCode = x.SubItem_Code;
            m.SubItemName = x.SubItem_Name;
            m.MaterialDescription = x.Material_Description;
            m.Qty = x.Qty;
            m.Unit = x.Unit;
            m.Amt = x.Amt;
            m.ETA = x.ETA;
            return Json(m);
        }


        [HttpGet]
        public virtual async Task<IActionResult> Warehouse()
        {
            var branch = await _workContext.GetCurrentBranch();
            List<WarehouseModel> warehouseModel = new List<WarehouseModel>();
            foreach (var item in branch.BranchWiseWarehouses)
            {
                WarehouseModel warehouse = new WarehouseModel();
                warehouse.WarehouseName = item.Warehouse.WarehouseName;
                warehouse.WarehouseCode = item.Warehouse.WarehouseCode;
                warehouse.Id = item.Warehouse.Id;
                List<WarehouseZoneAreaModel> ZoneList = new List<WarehouseZoneAreaModel>();
                foreach (var zone in item.Warehouse.WarehouseZones)
                {
                    var Zone = new WarehouseZoneAreaModel();
                    Zone.ZoneName = zone.ZoneName;
                    Zone.ZoneCode = zone.ZoneCode;
                    ZoneList.Add(Zone);

                }
                warehouse.ZoneAreaList = ZoneList;
                warehouseModel.Add(warehouse);
            }
            return Json(warehouseModel);
        }


        [HttpGet]
        public virtual IActionResult WarehouseZone(int warehouseid)
        {
            var areas = _warehouseService.GetAllZone(warehouseid);
            List<WarehouseZoneAreaModel> model = new List<WarehouseZoneAreaModel>();
            foreach (var item in areas.ToList())
            {
                WarehouseZoneAreaModel zone = new WarehouseZoneAreaModel();
                zone.ZoneName = item.ZoneName;
                zone.ZoneCode = item.ZoneCode;

                zone.Id = item.Id;
                model.Add(zone);
            }
            return Json(model);
        }

        [HttpGet]
        public virtual IActionResult WarehouseArea(int warehouseid, int zoneid)
        {
            var areas = _warehouseService.GetAllWarehouseArea(warehouseid, zoneid, true);
            List<WarehouseArea> model = new List<WarehouseArea>();
            foreach (var item in areas.ToList())
            {
                WarehouseArea area = new WarehouseArea();
                area.AreaName = item.AreaName;
                area.AreaCode = item.AreaCode;
                area.Size = Convert.ToInt32(item.Size);
                area.Id = item.Id;
                model.Add(area);
            }
            return Json(model);
        }
        [HttpPost]
        public virtual IActionResult Complete([FromBody] List<CreateModel> model)
        {
            var branch = _workContext.GetCurrentBranch().Result;
            var intranicRow = _intrasitService.GetById(model.FirstOrDefault().ItemId);
            var master = new GoodReceivedNoteMaster();
            master.PONo = model.FirstOrDefault().Ponumber;
            master.InvoiceDate = DateTime.Now;
            master.BranchCode = branch.BranchCode;
            master.InvoiceNo = model.FirstOrDefault().invoice;
            master.SenderCompany = intranicRow.Sender_Company;
            master.GRNNumberOfSAP = model.FirstOrDefault().GRNNumberOfSAP;
            master.IRN = model.FirstOrDefault().IRN;
            foreach (var item in model)
            {
                intranicRow = _intrasitService.GetById(item.ItemId);
                var details = new GoodReceivedNoteDetails()
                {

                    Amount = intranicRow.Amt,
                    AreaId = item.Warea,
                    Remark = item.Remark,
                    GoodReceivedNoteMaster = master,

WMSApp/WMSWebApp/Views/Grn/GrnPrint.cshtml
@model int
@using Application.Services.GRN;
@using Application.Services.PO;
@using Application.Services.WarehouseMaster;
@using Application.Services;

@inject IGoodReceivedNoteMasterService _goodReceivedNoteMasterService;
@inject ICompanyHelper _companyService;
@inject IWarehouseService _wareHouseService;

@{
    Layout = null;
    var GRN = _goodReceivedNoteMasterService.GetbyId(Model);
}
<html>

<head>
    <style>
        header {
            width: 4in;
            display: block;
            margin-left: auto;
            margin-right: auto;
            height: 1in;
        }

        body {
            margin: 0in 0in 0in 0in;
            width: 8.5in;
            height: 11in;
        }

        * {
            font-family: arial;
            font-size: 12px;
        }

        th {
            background-color: gray;
            color: white;
            font-weight: bold;
        }

        tfoot > tr {
            background-color: gray;            
            height: 2px;
        }

        td {
            vertical-align: top;
        }

        .store-info div {
            font-size: 1.2em;
        }

            .store-info div.company-name {
                font-size: 1.5em;
                font-weight: bold;
            }

        table.order-info td {
            padding: 2px 4px 2px 4px;
        }

        table.order-info tr td.label {
            font-weight: bold;
            text-align: right;
            border-right: solid 1px #c0c0c0;
        }

            table.order-info tr td.label.first {
            }

            table.order-info tr td.label.last {
            }

        table.line-items {
            margin-top: 0.1in;
            padding: 0.1in 0in 0.1in 0in;
        }

            table.line-items th {
                padding: 2px;
            }

        table.footer {
            border-top: solid 1px #707070;
        }

            table.footer td.label {
                font-weight: bold;
                text-align: right;
            }

        td.notes {
            padding: 0.1in;
            font-style: italic;
        }

        .barcode {
            font-family: "Free 3 of 9 Extended";
            font-size: 48pt;
        }
    </style>
</head>

<body>
    <!-- Order Header - THIS SECTION CAN BE MODIFIED AS NEEDED -->
    <header>
        <h2>WMS</h2><br>
    </header>
    <table cellspacing=0 cellpadding="2" border=0 style="width:8.5in">
        <thead>
            <tr>
                <th colspan="3">
                    Goods Received Note
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td colspan="2" style="width:4.5in" class="store-info">
                    @{
                        var companyInfo = _companyService.GetCompanyByCode(GRN.BranchCode);
                        var areaInfo = _wareHouseService.GetWarehouseZoneAreaById(GRN.GoodReceivedNoteDetails.FirstOrDefault().AreaId);
                    }
                    <div class="company-name">@companyInfo.CompanyName</div>
                    <div>Address<br />@companyInfo.Address</div>
                    <div>Location - @companyInfo.Location</div>
                    <div>Branch Code - @GRN.BranchCode</div>
                </td>
                <td style="width:3.5in;" align="right" valign="top">
                </td>
            </tr>
            <tr>
                <td style="height:0.15in"></td>
            </tr>
            <tr>                
                <td style="width:2.5in">
                    <table cellspacing="0" border="0" class="order-info">
                        <tr>
                            <td align="right" class="label first">GRN No. #</td>
                            <td>@GRN.Id</td>
                        </tr>                        
                        @* <tr>
                        <td align="right" class="label last">Ship Date</td>
                        <td>[Ship Date]</td>
                        </tr>*@
                    </table>
                </td>
            </tr>
        </tbody>
    </table>

    <!-- END Order Header -->

    <table cellspacing=0 cellpadding="2" border="0" style="width:100%" class="line-items">
        <thead>

            <!-- Order Items Header - THIS SECTION CAN BE MODIFIED AS NEEDED -->

            <tr>
                <th align="left" style="width:1.5in" class="sku">
                    PONo.
                </th>
                <th align="left" style="width:1.5in" class="sku">
                    Sub Item Code
                </th>
                <th align="left" style="width:1.5in" class="sku">
                    Area Name
                </th>
                <th align="left" style="width:1.5in" class="sku">
                    Remark
                </th>
                <th align="left" style="width:1.5in" class="sku">
                    Invoice No.
                </th>
                <th align="left">
                    Invoice Date
                </th>
                <th align="right" style="width:0.75in" class="price">
                    Quantity
                </th>
                <th align="center" style="width:0.75in">
                    Sender Company
                </th>
                <th align="right" style="width:0.75in" class="price">
                    GRN Number of SAP
                </th>
                <th align="right" style="width:0.75in" class="price">
                    IRN
                </th>
            </tr>

            <!-- END Order Items Header -->

        </thead>
        <tbody>
            @{
                foreach (var item in GRN.GoodReceivedNoteDetails)
                {
                    //var subitem = _subitemService.GetItemByCOde(item.SubItemCode);
                    //var location = _wareHouseService.GetWarehouseZoneAreaById(item.AreaId);
                    <tr>
                        <td class="sku">@GRN.PONo</td>
                        <td class="sku">@item.SubItemCode</td>
                        <td class="sku">@areaInfo.AreaName</td>
                        <td class="sku">@item.Remark</td>
                        <td class="sku">@GRN.InvoiceNo</td>
                        <td class="sku">@GRN.InvoiceDate</td>
                        <td align="right">@item.Qty</td>
                        <td align="center">@GRN.SenderCompany</td>
                        <td align="right">@GRN.GRNNumberOfSAP</td>
                        <td align="right">@GRN.IRN</td>
                    </tr>
                }

            }
           
            <!-- Order Items - THIS SECTION CAN BE MODIFIED AS NEEDED -->
            <!-- END Order Items -->

        </tbody>
        <tfoot>
            <tr>
                <td>Total Quantity</td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td>@GRN.GoodReceivedNoteDetails.Select(x => x.Qty).Sum()</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <!-- Order Footer - THIS SECTION CAN BE MODIFIED AS NEEDED -->    

    <!-- END Order Footer -->
    </div>

</body>

</html>

WMSApp/WMSWebApp/Views/Grn/List.cshtml
@using Domain.Model
@model List<Branch>
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Style{
    <link href="~/lib/kendoUi/2021/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="~/lib/kendoUi/2021/styles/kendo.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/kendoUi/2021/styles/kendo.default.min.css" rel="stylesheet" />
    <link href="~/lib/kendoUi/2021/styles/kendo.default.mobile.min.css" rel="stylesheet" />


}
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Grn List</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Process</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">GRN</h3>


                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="form-group row">
                                <div class="col-md-2">

                                    <label>Branch </label>
                                    <select class="form-control" id="branch" asp-items="@(new SelectList(Model,"BranchCode","BranchName"))"></select>

                                </div>

                            </div>
                            <div class="row">
                                <div class="col-md-2">
                                    <button class="btn btn-primary" id="search" type="button">Search</button>
                                </div>
                            </div>
                            <br />
                            <div id="user-grid">
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div>
    </section>


    @section Scripts{
    <environment include="Development">
        <script src="~/lib/kendoUi/2021/js/kendo.all.min.js"></script>
        <script src="~/lib/kendoUi/2021/js/jszip.min.js"></script>
        <script src="~/js/common.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="~/lib/kendoUi/2021/js/kendo.all.min.js"></script>
        <script src="~/lib/kendoUi/2021/js/jszip.min.js"></script>
        <script src="~/js/common.min.js"></script>


    </environment>

    <script>
        function additionalData() {
            var data = {
                branchCode: $("#branch").val(),
                //pnr: $("#pnr").val(),
                //bookingRefNo: $("#bookingRefNo").val(),
                //email: $("#email").val(),
                //mobile: $("#mobile").val(),
                //fromDate: $("#fromDate").val(),
                //toDate: $("#toDate").val(),
                //apisource:$("#apisource").val()
            }
            addAntiForgeryToken(data);
            return data;
        }
        $(document).ready(function(){
            $('#search').click(function () {
                //search
                var grid = $('#user-grid').data('kendoGrid');
                grid.dataSource.read();
                return false;
            });

            var initialLoad = true;
            $("#user-grid").kendoGrid({

                toolbar: ["excel"],
                excel: {
                    fileName: "GRN Export.xlsx",
                    proxyURL: "@Html.Raw(Url.Action("List", "GRN"))",
                    filterable: true
                },
                dataSource: {

                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("List", "GRN"))",
                            type: "POST",
                            dataType: "json",
                            data: additionalData,
                            complete: function (result) {
                                console.log("Remote built-in transport", result);
                                if (result.status == 401) {
                                    document.location.href = "@Html.Raw(Url.Action("Index", "AccessDenied"))";
                                }
                            }

                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function (e) {
                        //display_kendoui_grid_error(e);
                        // Cancel the changes
                        console.log(e)
                        this.cancelChanges();
                    },
                    pageSize: 20,
                    sortable: true,
                    serverPaging: true,
                    serverSorting: true,
                    requestStart: function () {
                        if (initialLoad) //<-- if it's the initial load, manually start the spinner
                            kendo.ui.progress($("#user-grid"), true);
                    },
                    requestEnd: function () {
                        if (initialLoad)
                            kendo.ui.progress($("#user-grid"), false);
                        initialLoad = false; //<-- make sure the spinner doesn't fire again (that would produce two spinners instead of one)

                    },

                },
                pageable: {
                    refresh: true,
                    pageSizes: true
                },
                excel: {
                    allPages: true
                },
                scrollable: false,
                columns: [{
                    field: "Id",
                    title: "ID",
                    width: 50
                },
                {
                    field: "PONo",
                    title: "PONo",
                    width: 50
                },

                {
                    field: "InvoiceNo",
                    title: "InvoiceNo",
                    width: 300
                },
                {
                    field: "InvoiceDate",
                    title: "InvoiceDate",
                    encoded: false,
                    width: 300
                },
                {
                    field: "Branch",
                    title: "Branch",
                    width: 300
                },
                {
                    field: "BranchCode",
                    title: "BranchCode",
                    width: 120
                },




                {
                    field: "SenderCompany",
                    title: "SenderCompany",
                    width: 50
                },
                {
                    title: "Action",
                    headerAttributes: { style: "text-align:center" },
                    attributes: { style: "text-align:center" },
                    template: '<a href="@(Url.Action("GrnPrint", "Grn"))/?id=#=Id#" class="btn btn-primary">Print</a>',
                    width: 100
                }




                    //{
                    //	title: "Action",
                    //	headerAttributes: { style: "text-align:center" },
                    //	template: '<a href="@(Url.Action("Edit", "Account"))/?id=#=Id#" class="btn btn-primary">Edit</a>',
                    //	width: 100
                    //},
                    //{
                    //    title: "Action",
                    //    headerAttributes: { style: "text-align:center" },
                    //    attributes: { style: "text-align:center" },
                    //    template: '<a href="@(Url.Action("CancelTicket", "AgentBooking"))/?id=#=ID#" class="btn btn-danger">Cancel</a>',
                    //    width: 100
                    //},
                    //{
                    //    title: "Action",
                    //    headerAttributes: { style: "text-align:center" },
                    //    attributes: { style: "text-align:center" },
                    //    template: '#if(BookingStatus=="PENDING"){#<a href="@(Url.Action("RejectBooking", "AgentBooking"))/?id=#=ID#" class="btn btn-danger">Reject</a>#}#',
                    //    width: 100
                    //},

                ],

            });
        });
        
    </script>
	}

